### ISSUE TITLE
The cluster binaries locations varies depending on Releases or Distributions

### ISSUE THREAD

**Issue by diegoakechi** [ClusterLabs/ha_cluster_exporter#87]
Depending on distro or on the service pack, the cluster binaries locations can vary, causing the exporter to not find the executable. For example, between SLE-12-SP3 and SLE-15, the binary `drbdsetup` has changed location and the exporter shows the following error:

```Oct 31 13:32:14 dev-1 ha_cluster_exporter[73317]: time="2019-10-31T13:32:14Z" level=warning msg="Could not initialize DRBD collector: '/usr/sbin/drbdsetup' not found: stat /usr/sbin/drbdsetup: n...r directory\n"```

And here we see the real location 
```
dev-1:~ # which drbdsetup
/sbin/drbdsetup
```

The exporter should allow different locations and ideally should try to find it by itself.

**Comment by ashleyprimo** [comment]
This could be solved using something such as `path, err := exec.LookPath("binary")`- I'll submit a PR for this (likely on Monday) if this is still open 👍

**Comment by diegoakechi** [comment]
Great @ashleyprimo. Thanks!

**Comment by MalloZup** [comment]
regarding PR and issue, I'm not sure if we are embarking on the good direction. Imho we should just use `command.exec`. https://golang.org/pkg/os/exec/#Command

In fact we are doing what already the command do , if you look at upstream doc: 

```
If name contains no path separators, Command uses LookPath to resolve name to a complete path if possible. Otherwise it uses name directly as Path. ```

IMHO the best approach would to remove the OS.stat and check if binary, steps and execute the cmd.exec, which will already uses LookPat.  If this fail, we can just adapt the error message that either binary was not found or the binary whatsoever wasn't executable. But this will allow us to be more clean without to many checks which we can spare imho in this scenario. (since cmd.exec uses already)

**Comment by ashleyprimo** [comment]
This is a very good point, makes sense that it would revert to `LookPath` natively; however, if were to just rely on the `exec` we would lose the ability to check if it's able to find the binary and if the binary is executable - since `os.Stat` relies on an absolute path.

Unless I'm missing something? :smiley:

**Comment by MalloZup** [comment]
ok but on highlevel point this 2 check what they would provide? if we can't execute the binary (because of lack of findings or is not exec) we have an IF which check the error , and  an error is throwed
